---
repos:
  # Set the list of basic git hooks to find and fix common problems in the current working tree.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
